apiVersion: "machine.openshift.io/v1beta1"
kind: Machine
metadata:
  name: master-machine
  labels:
    machine.openshift.io/cluster-api-cluster: azure-actuator
    machine.openshift.io/cluster-api-machine-role: worker
spec:
  versions:
    kubelet: 1.13.4
    controlPlane: 1.13.4
  providerSpec:
    value:
      apiVersion: azureprovider/v1alpha1
      kind: AzureMachineProviderSpec
      roles:
      - Master
      location: eastus2
      vmSize: Standard_B2ms
      image:
        resourceID: /resourceGroups/os4-common/providers/Microsoft.Compute/images/test1-controlplane-0-image-20190529150403
      osDisk:
        osType: "Linux"
        managedDisk:
          storageAccountType: "Premium_LRS"
        diskSizeGB: 60
      sshPublicKey: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDNEd4SGQ1L0pLZVJYMGZOMCt4YzM1eXhLdmtvb0Qwb0l2RnNCdDNHNTNaSXZlTWxwNUppQTRWT0Y3YjJ4cHZmL1FHbVpmWWl4d1JYMHdUKzRWUzYxV1ZNeUdZRUhPcE9QYy85MWZTcTg4bTJZbitBYVhTUUxTbFpaVkZJTDZsK296bjlRQ3NaSXhqSlpkTW5BTlRQdlhWMWpjSVNJeDhmU0pKeWVEdlhFU2FEQ2N1VjdPZTdvd01lVVpseCtUUEhkcU85eEV1OXFuREVYUXo1SUVQQUMwTElSQnVicmJVaTRQZUJFUlFieVBQd1p0Um9NN2pFZ3RuRFhDcmxYbXo2T0N3NXNiaE1FNEJCUVliVjBOV0J3Unl2bHJReDJtYzZHNnJjODJ6OWxJMkRKQ3ZJcnNkRW43NytQZThiWm1MVU83V0sxRUFyd2xXY0FiZU1kYUFkbzcgamNoYWxvdXBAZGhjcC0yNC0xNzAuYnJxLnJlZGhhdC5jb20K
      publicIP: true
      vnet: os4-common-vnet
      managedIdentity: os4-common-identity
      subnet: os4-common-node-subnet
      credentialsSecret:
        name: test
        namespace: default
      userDataSecret:
        name: master-user-data-secret
        namespace: default
